#include <glext.h>

PFNGLATTACHSHADERPROC glAttachShader;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLCLEARPROC glClear;
PFNGLCLEARCOLORPROC glClearColor;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLCULLFACEPROC glCullFace;
PFNGLDRAWARRAYSPROC glDrawArrays;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLGETPROGRAMIVPROC glGetProgramiv;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
PFNGLVIEWPORTPROC glViewport;

int glext_init(void* mod) {
  glAttachShader = (PFNGLATTACHSHADERPROC) glext_proc_addr(mod, "glAttachShader");
  if(!glAttachShader) return 1;
  glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC) glext_proc_addr(mod, "glBindAttribLocation");
  if(!glBindAttribLocation) return 2;
  glBindBuffer = (PFNGLBINDBUFFERPROC) glext_proc_addr(mod, "glBindBuffer");
  if(!glBindBuffer) return 3;
  glBufferData = (PFNGLBUFFERDATAPROC) glext_proc_addr(mod, "glBufferData");
  if(!glBufferData) return 4;
  glClear = (PFNGLCLEARPROC) glext_proc_addr(mod, "glClear");
  if(!glClear) return 5;
  glClearColor = (PFNGLCLEARCOLORPROC) glext_proc_addr(mod, "glClearColor");
  if(!glClearColor) return 6;
  glCompileShader = (PFNGLCOMPILESHADERPROC) glext_proc_addr(mod, "glCompileShader");
  if(!glCompileShader) return 7;
  glCreateProgram = (PFNGLCREATEPROGRAMPROC) glext_proc_addr(mod, "glCreateProgram");
  if(!glCreateProgram) return 8;
  glCreateShader = (PFNGLCREATESHADERPROC) glext_proc_addr(mod, "glCreateShader");
  if(!glCreateShader) return 9;
  glCullFace = (PFNGLCULLFACEPROC) glext_proc_addr(mod, "glCullFace");
  if(!glCullFace) return 10;
  glDrawArrays = (PFNGLDRAWARRAYSPROC) glext_proc_addr(mod, "glDrawArrays");
  if(!glDrawArrays) return 11;
  glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC) glext_proc_addr(mod, "glEnableVertexAttribArray");
  if(!glEnableVertexAttribArray) return 12;
  glGenBuffers = (PFNGLGENBUFFERSPROC) glext_proc_addr(mod, "glGenBuffers");
  if(!glGenBuffers) return 13;
  glGetProgramiv = (PFNGLGETPROGRAMIVPROC) glext_proc_addr(mod, "glGetProgramiv");
  if(!glGetProgramiv) return 14;
  glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC) glext_proc_addr(mod, "glGetShaderInfoLog");
  if(!glGetShaderInfoLog) return 15;
  glGetShaderiv = (PFNGLGETSHADERIVPROC) glext_proc_addr(mod, "glGetShaderiv");
  if(!glGetShaderiv) return 16;
  glLinkProgram = (PFNGLLINKPROGRAMPROC) glext_proc_addr(mod, "glLinkProgram");
  if(!glLinkProgram) return 17;
  glShaderSource = (PFNGLSHADERSOURCEPROC) glext_proc_addr(mod, "glShaderSource");
  if(!glShaderSource) return 18;
  glUseProgram = (PFNGLUSEPROGRAMPROC) glext_proc_addr(mod, "glUseProgram");
  if(!glUseProgram) return 19;
  glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC) glext_proc_addr(mod, "glVertexAttribPointer");
  if(!glVertexAttribPointer) return 20;
  glViewport = (PFNGLVIEWPORTPROC) glext_proc_addr(mod, "glViewport");
  if(!glViewport) return 21;
  return 0;
}
